package cn.teacy.ai.annotation;

import org.springframework.beans.factory.annotation.Qualifier;

import java.lang.annotation.*;

/**
 * A Spring {@link Qualifier} annotation designed for the precise injection of {@code CompiledGraph} beans
 * generated by a specific {@link GraphComposer}.
 *
 * <h3>Usage Examples</h3>
 *
 * <p><strong>1. Field Injection</strong></p>
 * <pre>
 * &#064;Autowired
 * &#064;CompiledFrom(GreetingGraphComposer.class)
 * private CompiledGraph greetingGraph;
 * </pre>
 *
 * <p><strong>2. Constructor Injection</strong></p>
 * <pre>
 * public MyService(@CompiledFrom(GreetingGraphComposer.class) CompiledGraph graph) {
 *     this.graph = graph;
 * }
 * </pre>
 *
 * @author Teacy
 * @see GraphComposer
 * @see com.alibaba.cloud.ai.graph.CompiledGraph
 * @since 0.3.1
 */
@Target({ElementType.FIELD, ElementType.PARAMETER, ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@Qualifier
public @interface CompiledFrom {

    Class<?> value();

}
